features: [ "MFCC","Spectrogram","MelSpectrogram" ]

model:
  model_path: "model/models"
  module_path: "model/modules"

warning:
  ignore: true  # whether to ignore warnings, true by default

dataset:
  k_fold: 4   # 4 by default
  repeat_times: 32  # 32 by default
  use_merge: true   # whether to use the merge files, true by default
  use_vad: true     # whether to generate the vad features, true by default
  random_disruption: true # whether to randomize, notice that this will not change the file for k-fold and is safe, true by default
  batch_size: 16     # batch size, 16 by default
  balance: false # balance the dataset, true by default
  use_argumentation: false

  process:
    sr: 16000     # sample rate, 16000 by default
    dim: 3        # dimensions, 3 means expand dims to tuple of shape 4 to process in image-like ways, 2 means not expand and process in test-embedding way, 3 by default
    crop_length: 25 # sample seconds, 5 by default
    normalized: true  # normalized, true by default

    argumentation:
      gaussian_noise:
        min_amplitude: 0.001
        max_amplitude: 0.015
        p: 0.5
      time_stretch:
        min_rate: 0.8
        max_rate: 1.25
        p: 0.5
      pitch_shift:
        min_semitones: -4
        max_semitones: 4
        p: 0.5
      shift:
        min_fraction: -0.5
        max_fraction: 0.5
        p: 0.5
    pre_emphasis:
      coefficient: 0.95
    mfcc:
      resize: true
      resize_height: 128
      resize_width: -1
      n_fft: 1024
      n_mfcc: 20
      n_mels: 128
      hop_length: 512
    specs:
      resize: true
      resize_height: 128
      resize_width: -1
      n_fft: 1024
      hop_length: 512
    melspecs:
      resize: true
      resize_height: 128
      resize_width: -1
      n_fft: 1024
      n_mels: 128
      hop_length: 512
    vad:
      percent_high_nrg: 0.5


image:
  image_dir: "image"

output:
  output_dir: "output"

log:
  log_dir: "log"

weight:
  weight_dir: "weight"