features: [ "MFCC","Spectrogram","MelSpectrogram" ]

process:
  sr: 16000
  crop_length: 5
  normalized: true
  pre_emphasis:
    coefficient: 0.95
  mfcc:
    resize: false
    resize_height: 128
    resize_width: -1
    n_fft: 1024
    n_mfcc: 20
    n_mels: 128
    hop_length: 512
  specs:
    resize: false
    resize_height: 128
    resize_width: -1
    n_fft: 1024
    hop_length: 512
  melspecs:
    resize: false
    resize_height: 128
    resize_width: -1
    n_fft: 1024
    n_mels: 128
    hop_length: 512


log:
  log_dir: "log"
